version: "3.3"

services:
  lets-fork:
    build: .
    command: gaper
    env_file: .env
    environment:
      CGO_ENABLED: 0
    volumes:
      - .:/go/src/github.com/peterzernia/lets-fork
    ports:
      - "8003:8003"
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  redis_data: