name: ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2
      # lint & test
      - name: Run lint & test
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo REDIS_URL=redis://:@redis >> .env
          echo API_TOKEN="$API_TOKEN" >> .env
          make lint
          make test
      # deploy
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontuseforce: false
          usedocker: false
          appdir: ""
          docker_heroku_process_type: "web"
      # publish
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: peterzernia/lets-fork
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}